//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petriss.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public int InstrumentId { get; set; }
        public string InstrumentName { get; set; }
        public string InstrumentDesc { get; set; }
        public int VendorId { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public int ManufacturerId { get; set; }
        public int SpecialityId { get; set; }
        public int InstrumentTypeId { get; set; }
        public string Finish { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public string Weight { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
