//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petriss.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string OrganizationLink { get; set; }
        public string OrganizationAddress1 { get; set; }
        public string OrganizationAddress2 { get; set; }
        public Nullable<int> OrganizationStateId { get; set; }
        public Nullable<int> OrganizationCityId { get; set; }
        public Nullable<int> OrganizationZip { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
