//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petriss.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetrissEntities : DbContext
    {
        public PetrissEntities()
            : base("name=PetrissEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrandMaster> BrandMasters { get; set; }
        public virtual DbSet<CityMaster> CityMasters { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<ManufacturerMaster> ManufacturerMasters { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<SoakNote> SoakNotes { get; set; }
        public virtual DbSet<SoakNoteMaster> SoakNoteMasters { get; set; }
        public virtual DbSet<SpecialityMaster> SpecialityMasters { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<StatusMaster> StatusMasters { get; set; }
        public virtual DbSet<UserLookupRole> UserLookupRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersProfile> UsersProfiles { get; set; }
        public virtual DbSet<UsersRole> UsersRoles { get; set; }
    }
}
