//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petriss.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PETUser
    {
        public int UserProfileID { get; set; }
        public string PrefferedName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string PasswordEncryptedText { get; set; }
        public bool ActivationStatus { get; set; }
        public string ActivationLink { get; set; }
        public Nullable<int> LoginAttempt { get; set; }
        public string TempPassword { get; set; }
        public bool TermsandConditionsStatus { get; set; }
        public Nullable<System.DateTime> RowCreatedDateTime { get; set; }
        public Nullable<System.DateTime> RowModifiedDateTime { get; set; }
    }
}
