//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petriss.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoakNote
    {
        public int SoakId { get; set; }
        public int TimeinSeconds { get; set; }
        public int TimeinMinutes { get; set; }
        public int TempreatureLow { get; set; }
        public int TempreatureHigh { get; set; }
        public string TempreatureType { get; set; }
        public int PhLevelLow { get; set; }
        public int PhLevelHigh { get; set; }
        public int SoakNoteId { get; set; }
        public string FinalNote { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
