//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petriss.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string VendorLink { get; set; }
        public string VendorAddress1 { get; set; }
        public string VendorAddress2 { get; set; }
        public Nullable<int> VendorStateId { get; set; }
        public Nullable<int> VendorCityId { get; set; }
        public Nullable<int> VendorZip { get; set; }
        public int CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int ModifiedByUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
